import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "theproeducator-demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="theme-color" content="#000000" />
      <meta name="description" content="Generated by create next app" />
      <meta name="application-name" content="theproeducator-demo" />
      <meta name="robots" content="noindex, nofollow" />
      <body
        className={`overflow-x-hidden hide-scrollbar antialiased`}
      >
        <NavBar />
        <main className="w-full min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
